/**
 * @zetesis/payload-indexer
 *
 * Generic document indexing library for Payload CMS. Embeddings are always
 * generated by the search backend (autoEmbed) — there is no client-side
 * embedding path. The library handles chunking, source extraction, sync
 * hooks, and sync-status reporting.
 */

// ============================================================================
// ADAPTER EXPORTS
// ============================================================================

export type {
  AdapterSearchResult,
  // Schema types
  BaseCollectionSchema,
  DeleteResult,
  IndexDocument,
  // Core adapter interface
  IndexerAdapter,
  // Type inference helper
  InferSchema,
  // Operation result types
  SyncResult,
  VectorSearchOptions
} from './adapter'

// ============================================================================
// CHUNKING EXPORTS
// ============================================================================

export { chunkMarkdown } from './embedding/chunking/strategies/markdown-chunker'
export {
  chunkText,
  shouldChunk
} from './embedding/chunking/strategies/text-chunker'
export type { ChunkOptions, TextChunk } from './embedding/chunking/types'
export type { IndexableCollectionConfig } from './plugin/types'

// ============================================================================
// DOCUMENT EXPORTS
// ============================================================================

export { mapPayloadDocumentToIndex } from './document/field-mapper'
export type {
  AutoEmbedConfig,
  BaseDocument,
  ChunkDocument,
  ChunkingConfig,
  CollectionConfig,
  EmbeddingTableConfig,
  FieldMapping,
  IndexedDocument,
  PayloadDocument,
  SourceField,
  TableConfig
} from './document/types'

// ============================================================================
// CORE EXPORTS
// ============================================================================

// Constants
export {
  DEFAULT_CHUNK_SIZE,
  DEFAULT_OVERLAP,
  MAX_CHUNK_SIZE,
  MIN_CHUNK_SIZE
} from './core/config/constants'
// Logging
export type { LogContext, LoggerConfig, LogLevel } from './core/logging/logger'
export {
  configureLogger,
  createLogger,
  getLogger,
  Logger,
  logger,
  setLogger
} from './core/logging/logger'
// Metrics
export type { MetricsEvent, SyncMetrics } from './core/metrics/sync-metrics'
export {
  getSyncMetrics,
  onMetricsUpdate,
  resetSyncMetrics
} from './core/metrics/sync-metrics'
export type {
  ChunkHeaderMetadata,
  ParsedChunk
} from './core/utils/chunk-format-utils'
// Utilities
export {
  CHUNK_HEADER_SEPARATOR,
  extractContentOnly,
  extractHeaderMetadata,
  formatChunkWithHeaders,
  parseChunkText
} from './core/utils/chunk-format-utils'

export { computeContentHash } from './core/utils/content-hash'
export { buildHeaderHierarchy } from './core/utils/header-utils'
export type { SummarizeLexicalConfig } from './core/utils/transforms'
export {
  createSummarizeLexicalTransform,
  createSummarizeTransform,
  type SummarizeConfig,
  transformLexicalToMarkdown
} from './core/utils/transforms'

// ============================================================================
// SYNC STATUS EXPORTS
// ============================================================================

export type {
  BatchSyncStatusResult,
  SyncStatusResult,
  SyncStatusValue
} from './sync-status'
export {
  checkBatchSyncStatus,
  checkSyncStatus,
  createSyncStatusEndpoints
} from './sync-status'

// ============================================================================
// HOOKS EXPORTS
// ============================================================================

export type { SyncHookContext } from './hooks'

// ============================================================================
// PLUGIN EXPORTS
// ============================================================================

// Plugin types
export type {
  IndexerFeatureConfig,
  IndexerPluginConfig,
  IndexerPluginResult,
  SearchFeatureConfig,
  SearchMode,
  SyncErrorContext,
  SyncFeatureConfig,
  SyncOptions
} from './plugin'
// Main factory
// Sync utilities (for custom implementations)
// Naming utilities
export {
  applySyncHooks,
  createIndexerPlugin,
  DocumentSyncer,
  deleteDocumentFromIndex,
  getIndexCollectionName,
  syncDocumentToIndex
} from './plugin'
