/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    taxonomy: Taxonomy;
    'mcp-search-tokens': McpSearchToken;
    agents: Agent;
    'llm-usage-events': LlmUsageEvent;
    documents: Document;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    taxonomy: TaxonomySelect<false> | TaxonomySelect<true>;
    'mcp-search-tokens': McpSearchTokensSelect<false> | McpSearchTokensSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'llm-usage-events': LlmUsageEventsSelect<false> | LlmUsageEventsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  publishedAt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Transforms to apply to the content text before indexing. Order matters.
   */
  text_transforms?: ('strip-urls' | 'strip-mentions' | 'normalize-whitespace')[] | null;
  categories?: (number | Taxonomy)[] | null;
  _syncStatus?: ('synced' | 'outdated' | 'not-indexed' | 'error') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy".
 */
export interface Taxonomy {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Metadata: types, permissions, selectable, etc.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-search-tokens".
 */
export interface McpSearchToken {
  id: number;
  user: number | User;
  /**
   * Optional. If set, every search made with this token is auto-scoped to these taxonomy slugs (forwarded as `x-taxonomy-slugs` to the MCP server).
   */
  taxonomies?: (number | Taxonomy)[] | null;
  /**
   * Descriptive name (e.g. "Claude Desktop").
   */
  label: string;
  tokenHash: string;
  /**
   * First chars of the token for identification.
   */
  tokenPrefix: string;
  /**
   * Last time this token authenticated a request.
   */
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  /**
   * Display name for the agent
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Enable or disable this agent
   */
  isActive?: boolean | null;
  /**
   * When enabled, anonymous channel callers (e.g. Telegram users not yet bound to a ZP user) can chat with this agent. Leave off to require a bound user.
   */
  allowGuestAccess?: boolean | null;
  /**
   * LLM model to use (e.g., openai/gpt-4o, anthropic/claude-sonnet-4-20250514)
   */
  llmModel: string;
  /**
   * API Key for the LLM provider (encrypted at rest)
   */
  apiKey: string;
  /**
   * Last 4 characters of the API key (auto-computed)
   */
  apiKeyFingerprint?: string | null;
  /**
   * System prompt that defines the agent personality and constraints
   */
  systemPrompt: string;
  /**
   * Max tool calls per turn. Leave empty for no limit.
   */
  toolCallLimit?: number | null;
  /**
   * Collections to search for RAG context
   */
  searchCollections?: 'posts_chunk'[] | null;
  /**
   * Taxonomies that filter the RAG content. REQUIRED: if empty, agent will not search any content.
   */
  taxonomies?: (number | Taxonomy)[] | null;
  /**
   * Number of chunks to retrieve for RAG context
   */
  kResults?: number | null;
  /**
   * Maximum context size in bytes (default: 64KB)
   */
  maxContextBytes?: number | null;
  /**
   * TTL for conversation history in seconds (default: 24h)
   */
  ttl?: number | null;
  /**
   * Avatar image for the agent
   */
  avatar?: (number | null) | Media;
  /**
   * Welcome message title displayed when starting a new chat
   */
  welcomeTitle?: string | null;
  /**
   * Welcome message subtitle displayed when starting a new chat
   */
  welcomeSubtitle?: string | null;
  /**
   * Suggested questions to help users get started
   */
  suggestedQuestions?:
    | {
        /**
         * The full prompt text to send when clicked
         */
        prompt: string;
        /**
         * Short title for the suggestion
         */
        title: string;
        /**
         * Brief description of what the question is about
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-usage-events".
 */
export interface LlmUsageEvent {
  id: number;
  /**
   * User who triggered the run
   */
  user: number | User;
  /**
   * Agent FK (may be null if agent was deleted)
   */
  agent?: (number | null) | Agent;
  /**
   * Persisted independently so records survive agent deletion
   */
  agentSlug?: string | null;
  /**
   * Agno session_id — groups messages into a conversation
   */
  conversationId?: string | null;
  /**
   * Agno run_id — unique per event
   */
  runId?: string | null;
  provider: 'anthropic' | 'openai' | 'google';
  model: string;
  apiKeySource: 'agent' | 'user';
  /**
   * Last 4 chars of the API key used. Never store the raw key.
   */
  apiKeyFingerprint?: string | null;
  inputTokens: number;
  outputTokens: number;
  cachedInputTokens?: number | null;
  totalTokens: number;
  costUsd: number;
  startedAt?: string | null;
  completedAt: string;
  latencyMs?: number | null;
  status: 'success' | 'error';
  errorCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documents parsed to markdown via LlamaParse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  parse_status?: ('idle' | 'pending' | 'processing' | 'done' | 'error') | null;
  parse_job_id?: string | null;
  parsed_at?: string | null;
  parse_error?: string | null;
  /**
   * Optional language hint for OCR (e.g. "es", "en").
   */
  language?: string | null;
  /**
   * LlamaParse mode passed as `parse_mode`. Page-level is fast + per-page; document-level is slower but reasons across the whole doc. See https://docs.cloud.llamaindex.ai/llamaparse/parameters/parse_mode
   */
  mode?:
    | (
        | 'parse_page_without_llm'
        | 'parse_page_with_llm'
        | 'parse_page_with_lvm'
        | 'parse_page_with_agent'
        | 'parse_page_with_layout_agent'
        | 'parse_document_with_llm'
        | 'parse_document_with_lvm'
        | 'parse_document_with_agent'
      )
    | null;
  /**
   * Free-form instruction to guide LlamaParse (e.g. "preserve tables").
   */
  parsing_instruction?: string | null;
  /**
   * Markdown returned by LlamaParse. Editable.
   */
  parsed_text?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'taxonomy';
        value: number | Taxonomy;
      } | null)
    | ({
        relationTo: 'mcp-search-tokens';
        value: number | McpSearchToken;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'llm-usage-events';
        value: number | LlmUsageEvent;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  publishedAt?: T;
  content?: T;
  text_transforms?: T;
  categories?: T;
  _syncStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy_select".
 */
export interface TaxonomySelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-search-tokens_select".
 */
export interface McpSearchTokensSelect<T extends boolean = true> {
  user?: T;
  taxonomies?: T;
  label?: T;
  tokenHash?: T;
  tokenPrefix?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  allowGuestAccess?: T;
  llmModel?: T;
  apiKey?: T;
  apiKeyFingerprint?: T;
  systemPrompt?: T;
  toolCallLimit?: T;
  searchCollections?: T;
  taxonomies?: T;
  kResults?: T;
  maxContextBytes?: T;
  ttl?: T;
  avatar?: T;
  welcomeTitle?: T;
  welcomeSubtitle?: T;
  suggestedQuestions?:
    | T
    | {
        prompt?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-usage-events_select".
 */
export interface LlmUsageEventsSelect<T extends boolean = true> {
  user?: T;
  agent?: T;
  agentSlug?: T;
  conversationId?: T;
  runId?: T;
  provider?: T;
  model?: T;
  apiKeySource?: T;
  apiKeyFingerprint?: T;
  inputTokens?: T;
  outputTokens?: T;
  cachedInputTokens?: T;
  totalTokens?: T;
  costUsd?: T;
  startedAt?: T;
  completedAt?: T;
  latencyMs?: T;
  status?: T;
  errorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  parse_status?: T;
  parse_job_id?: T;
  parsed_at?: T;
  parse_error?: T;
  language?: T;
  mode?: T;
  parsing_instruction?: T;
  parsed_text?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}