/**
 * Generic indexer plugin factory
 * Creates a Payload CMS plugin that handles document syncing to any search backend
 */

import type { CollectionConfig, Config } from 'payload'
import type { IndexerAdapter } from '../adapter/types'
import { Logger } from '../core/logging/logger'
import type { FieldMapping, PayloadDocument, TableConfig } from '../document/types'
import { createSyncStatusEndpoints } from '../sync-status/create-sync-status-endpoint'
import { checkSyncStatus } from '../sync-status/sync-status-service'
import type { SyncStatusValue } from '../sync-status/types'
import { applySyncHooks } from './sync/hooks'
import type { IndexerPluginConfig, SyncFeatureConfig } from './types'

/**
 * Result of plugin creation containing the plugin function and the adapter
 */
export interface IndexerPluginResult {
  /** The Payload plugin function */
  plugin: (config: Config) => Config
  /** The adapter instance */
  adapter: IndexerAdapter
}

/**
 * Creates an indexer plugin for Payload CMS.
 *
 * Embeddings are always generated by the search backend (autoEmbed). The
 * plugin only chunks the source text and writes indexed documents; vectors
 * are produced server-side by the backend on upsert and on query.
 *
 * @example
 * ```typescript
 * import { createIndexerPlugin } from '@zetesis/payload-indexer';
 * import { createTypesenseAdapter } from '@zetesis/payload-typesense';
 *
 * const adapter = createTypesenseAdapter({ apiKey: '...', nodes: [...] });
 *
 * const { plugin } = createIndexerPlugin({
 *   adapter,
 *   features: { sync: { enabled: true } },
 *   collections: {
 *     posts: [{
 *       enabled: true,
 *       fields: [{ name: 'title', type: 'string' }],
 *       embedding: {
 *         fields: ['content'],
 *         chunking: { strategy: 'markdown' },
 *         autoEmbed: {
 *           from: ['chunk_text'],
 *           modelConfig: { modelName: 'openai/text-embedding-3-small', apiKey: '...' }
 *         }
 *       }
 *     }]
 *   }
 * });
 *
 * export default buildConfig({ plugins: [plugin] });
 * ```
 */
export function createIndexerPlugin<TFieldMapping extends FieldMapping>(
  config: IndexerPluginConfig<TFieldMapping>
): IndexerPluginResult {
  const { adapter, features, collections } = config
  const logger = new Logger({ enabled: true, prefix: '[payload-indexer]' })

  const plugin = (payloadConfig: Config): Config => {
    if (payloadConfig.collections && features.sync?.enabled) {
      payloadConfig.collections = applySyncHooks(payloadConfig.collections, config, adapter)

      logger.debug('Sync hooks applied to collections', {
        collectionsCount: Object.keys(collections).length
      })
    }

    if (features.sync?.enabled) {
      const syncStatusEndpoints = createSyncStatusEndpoints({ adapter, collections })
      payloadConfig.endpoints = [...(payloadConfig.endpoints || []), ...syncStatusEndpoints]

      if (payloadConfig.collections) {
        payloadConfig.collections = injectSyncStatusField(
          payloadConfig.collections,
          collections,
          adapter,
          features.sync
        )
      }

      logger.debug('Sync status endpoints and virtual fields registered')
    }

    return payloadConfig
  }

  return { plugin, adapter }
}

/**
 * Creates an afterRead hook that computes sync status by comparing content hashes with the index
 */
function createSyncStatusAfterRead(adapter: IndexerAdapter, collectionSlug: string, tableConfigs: TableConfig[]) {
  return async ({ siblingData }: { siblingData: Record<string, unknown> }): Promise<SyncStatusValue> => {
    if (!siblingData?.id) return 'not-indexed'

    const enabledConfig = tableConfigs.find(tc => tc.enabled)
    if (!enabledConfig) return 'not-indexed'

    try {
      const result = await checkSyncStatus(
        adapter,
        collectionSlug,
        siblingData as unknown as PayloadDocument,
        enabledConfig
      )
      return result.status
    } catch {
      return 'error'
    }
  }
}

/**
 * Injects the _syncStatus virtual field into collections that have indexer tables configured
 */
function injectSyncStatusField(
  payloadCollections: CollectionConfig[],
  indexedCollections: Record<string, TableConfig[]>,
  adapter: IndexerAdapter,
  syncConfig?: SyncFeatureConfig
): CollectionConfig[] {
  return payloadCollections.map(collection => {
    const tableConfigs = indexedCollections[collection.slug]
    if (!tableConfigs) return collection

    // Per-collection `admin.defaultColumns` wins over the global sync default
    // — the global is a fallback for collections that haven't picked their
    // own admin columns. Inverting this would silently override every
    // collection's bespoke list (filename/parse_status for documents, etc).
    const defaultColumns = collection.admin?.defaultColumns ?? syncConfig?.defaultColumns

    return {
      ...collection,
      admin: {
        ...collection.admin,
        ...(defaultColumns ? { defaultColumns } : {})
      },
      fields: [
        ...(collection.fields || []),
        {
          name: '_syncStatus',
          label: 'Typesense Sync',
          type: 'select' as const,
          virtual: true,
          options: [
            { label: 'Synced', value: 'synced' },
            { label: 'Outdated', value: 'outdated' },
            { label: 'Not Indexed', value: 'not-indexed' },
            { label: 'Error', value: 'error' }
          ],
          hooks: {
            afterRead: [createSyncStatusAfterRead(adapter, collection.slug, tableConfigs)]
          },
          admin: {
            position: 'sidebar',
            components: {
              Field: '@zetesis/payload-indexer/client#SyncStatusField',
              Cell: '@zetesis/payload-indexer/client#SyncStatusCell'
            }
          }
        }
      ]
    }
  })
}
