/**
 * Document syncer - syncs Payload documents to the index using the adapter
 */

import type { IndexDocument, IndexerAdapter } from '../../adapter/types'
import { logger } from '../../core/logging/logger'
import { recordDeletion, recordSyncSuccess } from '../../core/metrics/sync-metrics'
import { formatChunkWithHeaders } from '../../core/utils/chunk-format-utils'
import { computeContentHash } from '../../core/utils/content-hash'
import { buildHeaderHierarchy } from '../../core/utils/header-utils'
import { mapPayloadDocumentToIndex } from '../../document/field-mapper'
import type { PayloadDocument, TableConfig } from '../../document/types'
import { chunkMarkdown, chunkText } from '../../embedding/chunking/strategies'
import type { TextChunk } from '../../embedding/chunking/types'
import { getIndexCollectionName } from '../utils/naming'

/**
 * Syncs a Payload document to the index. Embeddings are always generated by
 * the search backend (autoEmbed) — this function only chunks the source text
 * and writes indexed documents.
 */
export const syncDocumentToIndex = async (
  adapter: IndexerAdapter,
  collectionSlug: string,
  doc: PayloadDocument,
  operation: 'create' | 'update',
  tableConfig: TableConfig
) => {
  const tableName = getIndexCollectionName(collectionSlug, tableConfig)

  logger.debug('Syncing document to index', {
    documentId: doc.id,
    collection: collectionSlug,
    tableName,
    operation
  })

  const syncer = new DocumentSyncer(adapter, collectionSlug, tableName, tableConfig)
  await syncer.sync(doc, operation)

  logger.info('Document synced successfully to index', {
    documentId: doc.id,
    collection: collectionSlug,
    tableName,
    operation
  })
}

/**
 * Deletes a document and all associated chunks from one or more tables for a collection
 * @param adapter - The indexer adapter to use
 * @param collectionSlug - The Payload collection slug
 * @param docId - The document ID to delete
 * @param tableConfigs - One or more table configurations for the collection
 */
export const deleteDocumentFromIndex = async (
  adapter: IndexerAdapter,
  collectionSlug: string,
  docId: string,
  tableConfigs: TableConfig | TableConfig[]
) => {
  const configs = Array.isArray(tableConfigs) ? tableConfigs : [tableConfigs]
  let deleted = false
  for (const tableConfig of configs) {
    const tableName = getIndexCollectionName(collectionSlug, tableConfig)
    try {
      // Si la tabla es de chunks (embedding.chunking), borra solo por parent_doc_id
      if (tableConfig.embedding?.chunking) {
        logger.debug('Deleting all chunks by parent_doc_id', {
          parent_doc_id: docId,
          tableName
        })
        await adapter.deleteDocumentsByFilter(tableName, {
          parent_doc_id: docId
        })
        logger.info('All chunks deleted for document', {
          documentId: docId,
          tableName
        })
        deleted = true
      } else {
        // Tabla principal: borra por id y si no existe, intenta por parent_doc_id
        try {
          await adapter.deleteDocument(tableName, docId)
          logger.info('Document deleted from index', {
            documentId: docId,
            tableName
          })
          deleted = true
        } catch (_docDeleteError: unknown) {
          logger.debug('Document not found, attempting to delete chunks', {
            documentId: docId,
            tableName
          })
          try {
            await adapter.deleteDocumentsByFilter(tableName, {
              parent_doc_id: docId
            })
            logger.info('All chunks deleted for document', {
              documentId: docId,
              tableName
            })
          } catch (_chunkDeleteError: unknown) {
            logger.debug('No chunks found to delete', { documentId: docId })
          }
        }
      }
    } catch (error: unknown) {
      logger.error('Failed to delete document from index', error as Error, {
        documentId: docId,
        collection: collectionSlug,
        tableName
      })
    }
  }
  if (deleted) recordDeletion(collectionSlug, docId)
}

/**
 * Document syncer class that handles the actual sync logic
 */
export class DocumentSyncer {
  constructor(
    private adapter: IndexerAdapter,
    private collectionSlug: string,
    private tableName: string,
    private config: TableConfig
  ) {}

  async sync(doc: PayloadDocument, operation: 'create' | 'update'): Promise<void> {
    logger.debug(`Syncing document ${doc.id} to table ${this.tableName}`)

    if (this.config.embedding?.chunking) {
      await this.syncChunked(doc, operation)
    } else {
      await this.syncDocument(doc)
    }
  }

  private async syncDocument(doc: PayloadDocument): Promise<void> {
    const mappedFields = await mapPayloadDocumentToIndex(doc, this.config.fields)

    const sourceText = this.config.embedding?.fields ? await this.extractSourceText(doc) : ''
    const contentHash = sourceText ? computeContentHash(sourceText) : undefined

    const indexDoc: Record<string, unknown> = {
      ...mappedFields,
      id: String(doc.id),
      slug: doc.slug || '',
      createdAt: new Date(doc.createdAt).getTime(),
      updatedAt: new Date(doc.updatedAt).getTime(),
      ...(doc.publishedAt && { publishedAt: new Date(doc.publishedAt).getTime() }),
      ...(contentHash && { content_hash: contentHash })
    }

    await this.adapter.upsertDocument(this.tableName, indexDoc as IndexDocument)

    recordSyncSuccess(this.collectionSlug, String(doc.id))
    logger.info(`Synced document ${doc.id} to ${this.tableName}`)
  }

  private async syncChunked(doc: PayloadDocument, operation: 'create' | 'update'): Promise<void> {
    const sourceText = await this.extractSourceText(doc)
    if (!sourceText) {
      logger.warn(`No source text found for document ${doc.id}`)
      return
    }

    const contentHash = computeContentHash(sourceText)
    const chunks = await this.generateChunks(sourceText)

    const fields = this.config.fields ? await mapPayloadDocumentToIndex(doc, this.config.fields) : {}
    fields.slug = doc.slug || ''
    fields.publishedAt = doc.publishedAt ? new Date(doc.publishedAt).getTime() : undefined

    const chunkDocs = await this.buildAllChunkDocuments(chunks, doc, contentHash, fields)

    if (chunkDocs.length === 0) {
      logger.warn(`No chunks produced for document ${doc.id}`)
      return
    }

    if (operation === 'update') {
      await this.adapter.deleteDocumentsByFilter(this.tableName, { parent_doc_id: String(doc.id) })
    }

    await this.adapter.upsertDocuments(this.tableName, chunkDocs)

    recordSyncSuccess(this.collectionSlug, String(doc.id), chunkDocs.length)
    logger.info(`Synced ${chunkDocs.length} chunks for document ${doc.id} to ${this.tableName}`)
  }

  private async buildAllChunkDocuments(
    chunks: TextChunk[],
    doc: PayloadDocument,
    contentHash: string,
    fields: Record<string, unknown>
  ): Promise<IndexDocument[]> {
    return chunks.map(chunk => this.buildChunkDocument(chunk, doc, contentHash, fields))
  }

  private buildChunkDocument(
    chunk: TextChunk,
    doc: PayloadDocument,
    contentHash: string,
    fields: Record<string, unknown>
  ): IndexDocument {
    const headers = buildHeaderHierarchy(chunk.metadata)
    let formattedText = formatChunkWithHeaders(chunk.text, headers)

    if (this.config.embedding?.chunking?.interceptResult) {
      formattedText = this.config.embedding.chunking.interceptResult({ ...chunk, headers, formattedText }, doc)
    }

    return {
      id: `${doc.id}_chunk_${chunk.index}`,
      parent_doc_id: String(doc.id),
      chunk_index: chunk.index,
      chunk_text: formattedText,
      is_chunk: true,
      headers,
      createdAt: new Date(doc.createdAt).getTime(),
      updatedAt: new Date(doc.updatedAt).getTime(),
      content_hash: contentHash,
      ...fields
    } as IndexDocument
  }

  /**
   * Extract and transform source fields used to build chunks (and the
   * content hash). With autoEmbed, the backend reads the indexed
   * `chunk_text` to produce the vector — these source fields are not sent
   * verbatim, only the chunked output is.
   */
  private async extractSourceText(doc: PayloadDocument): Promise<string> {
    if (!this.config.embedding?.fields) return ''

    const textParts: string[] = []

    for (const sourceField of this.config.embedding.fields) {
      let fieldName: string
      let transform: ((value: unknown, ...args: unknown[]) => unknown | Promise<unknown>) | undefined

      if (typeof sourceField === 'string') {
        fieldName = sourceField
      } else {
        fieldName = sourceField.field
        transform = sourceField.transform
      }

      let val = doc[fieldName]

      if (transform) {
        val = await transform(val, doc)
      } else if (typeof val === 'object' && val !== null && 'root' in val) {
        val = JSON.stringify(val)
      }

      textParts.push(String(val || ''))
    }

    return textParts.join('\n\n')
  }

  private async generateChunks(text: string) {
    if (!this.config.embedding?.chunking) return []

    const { strategy, size, overlap } = this.config.embedding.chunking
    const options = { maxChunkSize: size, overlap }

    if (strategy === 'markdown') {
      return await chunkMarkdown(text, options)
    } else {
      return await chunkText(text, options)
    }
  }
}
