import type { CollectionConfig, Payload, PayloadRequest } from 'payload'

/**
 * Context passed to `buildSessionId` when a new chat starts.
 *
 * The consumer uses this context to assemble whatever session identifier
 * its storage layer expects. There are no format constraints — the same
 * string is later fed back to `validateSessionOwnership`.
 */
export interface BuildSessionIdContext {
  user: Record<string, unknown>
  agentSlug: string
  /** Present when the client is trying to continue an existing chat. */
  chatId?: string
  payload: Payload
  req: PayloadRequest
}

/**
 * Context passed to `validateSessionOwnership` whenever an endpoint
 * receives a session id from the client.
 */
export interface ValidateSessionOwnershipContext {
  user: Record<string, unknown>
  payload: Payload
  req: PayloadRequest
}

export type BuildSessionId = (ctx: BuildSessionIdContext) => Promise<string> | string

export type ValidateSessionOwnership = (
  sessionId: string,
  ctx: ValidateSessionOwnershipContext
) => Promise<boolean> | boolean

/**
 * Transform the Agents collection config generated by the plugin.
 *
 * The function receives the full `CollectionConfig` and must return a new
 * config. Spread the current value to keep the plugin's defaults and only
 * override what you need — the plugin will not merge the result back.
 */
export type CollectionOverrides = (current: CollectionConfig) => CollectionConfig

/**
 * Plugin configuration for `agentPlugin()`.
 */
export interface AgentPluginConfig {
  /**
   * Base URL of the Agno agent-runtime service.
   * @example 'http://agent-runtime:8000'
   */
  runtimeUrl: string

  /**
   * Shared secret for internal communication with the agent-runtime.
   * Sent as `X-Internal-Secret` header on runtime requests.
   */
  runtimeSecret?: string

  /**
   * Token budget callback. The consumer decides the billing logic —
   * the plugin only enforces the returned limit.
   *
   * Return the maximum number of tokens the user may consume today.
   */
  getDailyLimit: (payload: Payload, userId: string | number) => Promise<number>

  /**
   * Build the session id for a new chat, or derive/return the id for an
   * existing one. The returned string is forwarded to the agent-runtime
   * as `session_id` and is what clients echo back as `chatId`.
   *
   * Defaults to `${agentSlug}:${userId}:${uuid}` when omitted.
   */
  buildSessionId?: BuildSessionId

  /**
   * Validate that the current user owns `sessionId`. Called whenever an
   * endpoint receives a session id from the client (continue chat, load
   * history, rename, delete). Return `false` to reject with HTTP 403.
   *
   * Defaults to checking that `sessionId` contains `:${userId}:` — enough
   * for the default `buildSessionId` format. If you override the builder,
   * override this too.
   */
  validateSessionOwnership?: ValidateSessionOwnership

  /**
   * Override the Payload collection slug. Default: `'agents'`.
   */
  collectionSlug?: string

  /**
   * Override the endpoint base path. Default: `'/agents'`.
   *
   * All endpoints are registered under this prefix:
   * - `POST {basePath}` (chat)
   * - `GET  {basePath}/sessions`
   * - `GET/PATCH/DELETE {basePath}/session`
   * - `GET  {basePath}/agents`
   */
  basePath?: string

  /**
   * Encryption key for API keys stored in the Agents collection.
   * When provided, API keys are encrypted at rest using AES-256-GCM.
   * When omitted, API keys are stored in plaintext.
   */
  encryptionKey?: string

  /**
   * Slug of the `media` collection for agent avatars. Required — the plugin
   * no longer guesses; you must pass the slug you use in your config so a
   * rename elsewhere fails at boot instead of silently breaking uploads.
   */
  mediaCollectionSlug: string

  /**
   * Slug of the taxonomy collection for RAG filtering. Required — the plugin
   * no longer guesses; you must pass the slug you use in your config so a
   * rename elsewhere fails at boot instead of silently breaking the
   * taxonomies relationship on agents.
   */
  taxonomyCollectionSlug: string

  /**
   * Transform the Agents collection config before it is registered.
   *
   * Receives the full collection generated by the plugin. Spread it and
   * override only what you need — whatever you return replaces the
   * plugin's output verbatim.
   *
   * @example
   * ```ts
   * collectionOverrides: (current) => ({
   *   ...current,
   *   access: {
   *     ...current.access,
   *     create: ({ req }) => isAdmin(req.user),
   *   },
   * })
   * ```
   */
  collectionOverrides?: CollectionOverrides
}

// ── Source types ───────────────────────────────────────────────────────────

export interface Source {
  id: string
  title: string
  slug: string
  type: string
}

// ── Token usage types ─────────────────────────────────────────────────────

export interface DailyTokenUsage {
  date: string
  /** Cost-weighted effective tokens (cached input at 25%, output at 100%). */
  tokens_used: number
  /** Raw total from Agno (input + output, no weighting). */
  raw_total_tokens: number
  input_tokens: number
  output_tokens: number
  cache_read_tokens: number
  reasoning_tokens: number
  reset_at: string
}

export interface TokenUsageResult {
  limit: number
  used: number
  remaining: number
  percentage: number
  reset_at: string
  canUse: (tokens: number) => boolean
}

// ── Internal resolved config (all defaults applied) ───────────────────────

export interface ResolvedPluginConfig {
  runtimeUrl: string
  runtimeSecret: string
  getDailyLimit: (payload: Payload, userId: string | number) => Promise<number>
  buildSessionId: BuildSessionId
  validateSessionOwnership: ValidateSessionOwnership
  collectionSlug: string
  basePath: string
  encryptionKey: string | undefined
  mediaCollectionSlug: string
  taxonomyCollectionSlug: string
  collectionOverrides: CollectionOverrides | undefined
}
